Resources:
  SampleDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: twitter-management
      AttributeDefinitions:
        - AttributeName: HASH
          AttributeType: S
        - AttributeName: GSI1HASH
          AttributeType: S
        - AttributeName: GSI1RANGE
          AttributeType: S
        - AttributeName: GSI2HASH
          AttributeType: S
        - AttributeName: GSI2RANGE
          AttributeType: S
      KeySchema:
        - AttributeName: HASH
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1HASH
              KeyType: HASH
            - AttributeName: GSI1RANGE
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2HASH
              KeyType: HASH
            - AttributeName: GSI2RANGE
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
