Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      RoleName: twitter_management_lambda_role
  LambdaTweetFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: twitter-management-lambda
        S3Key: f31f61bfb6cc42c14a1f871aa1aa2888
      FunctionName: twitter-management-tweet
      Handler: tweet.tweet
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
      Runtime: nodejs18.x
