export const AWS_CONFIG = {
  REGION: "ap-northeast-1",
  ACCESS_KEY_ID: process.env.APP_AWS_ACCESS_KEY_ID,
  SECRET_ACCESS_KEY_ID: process.env.APP_AWS_SECRET_ACCESS_KEY,
  TABLE_NAME: "twitter-management",
  LOGICAL_TABLES: {
    CREDENTIAL: "CREDENTIAL",
    SCHEDULED_TWEET: "SCHEDULED_TWEET",
    SCHEDULED_RETWEET: "SCHEDULED_RETWEET",
    SCHEDULED_LIKE: "SCHEDULED_LIKE",
    EXECUTED_TWEET: "EXECUTED_TWEET",
    EXECUTED_RETWEET: "EXECUTED_RETWEET",
    EXECUTED_LIKE: "EXECUTED_LIKE",
  },
  LAMBDA_FUNCTION_NAME: {
    TWEET: "twitter-management-tweet",
    DELETE_TWEET: "twitter-management-deleteTweet",
  },
} as const;
